Add new linters scss_lint and coffeelint
Fix scss_lint warning

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -4,7 +4,13 @@ NONE='\033[0m'
 RED='\033[0;31m'
 WHITE='\033[1;37m'
 
-coffeelint app/assets/javascripts
+scss-lint app/assets/stylesheets
+if [ $? -ne 0 ]; then
+  echo "${WHITE}scss-lint ${RED}failed${NONE}"
+  exit 1
+fi
+
+bundle exec rake coffeelint app/assets/javascripts
 if [ $? -ne 0 ]; then
   echo "${WHITE}coffeelint ${RED}failed${NONE}"
   exit 1
