Update git pre-hooks
I added Zeitwerk check to pre-push.
We do not want to deviate from the Rails convention
when extending the structure of the application.

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -28,7 +28,13 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-bundle exec rake spec
+bundle exec rails zeitwerk:check
+if [ $? -ne 0 ]; then
+  echo "${WHITE}Zeitwerk compatibility ${RED}failed${NONE}"
+  exit 1
+fi
+
+bundle exec rspec spec
 if [ $? -ne 0 ]; then
   echo "${WHITE}test (rspec) ${RED}failed${NONE}"
   exit 1
