Add check health of translations to git hook
> `i18n-tasks health` checks if any keys are missing or not used, [1]
> that interpolations variables are consistent across locales,
> and that all the locale files are normalized (auto-formatted).

We want to ensure that our translations do not have missing values.
We know they may not be perfect, but according to the rule:
"worse is better". [2]

[1]: https://github.com/glebm/i18n-tasks
[2]: https://en.wikipedia.org/wiki/Worse_is_better

diff --git a/scripts/githooks/pre-push b/scripts/githooks/pre-push
--- a/scripts/githooks/pre-push
+++ b/scripts/githooks/pre-push
@@ -22,6 +22,12 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+bundle exec i18n-tasks health
+if [ $? -ne 0 ]; then
+  echo "${WHITE}i18n-tasks health ${RED}failed${NONE}"
+  exit 1
+fi
+
 bundle exec rails_best_practices --silent
 if [ $? -ne 0 ]; then
   echo "${WHITE}rails_best_practices ${RED}failed${NONE}"
